baseurl = "https://semba-blog.netlify.com/"
languageCode = "en-us"
title = "Masumbuko Semba"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "Semba"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:month/:day/:year/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Links"
    url = "/links/" 
    weight = 6
    
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
    
[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 4
    
[[menu.main]]
    name = "Publications"
    url = "/publication/"
    weight = 3
    
#[[menu.main]]
  #  name = "Teaching"
   # url = "/teaching/"
    
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/lugoga/masumbuko"
    weight = 5


[params]
    description = "A blog that deals with R scripting for Marine Environmental issues."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "grani_logo-01.png"
    width = 50
    height = 50
    alt = "Logo"

