---
title: Publishing Our Academic  Dissertation to Broad Audiences
author: Masumbuko Semba
date: '2018-11-14'
slug: publishing-our-academic-dissertation-to-broad-audiences
categories:
  - R
tags:
  - Masumbuko Semba
  - Bookdown
bibliography: [blog.bib, argo.bib]
csl: apa.csl
link-citations: yes
---

For years I used Word Processors to prepare manuscript for publication and report. And I used Adobe Indesign whenever I was consulted for typsetting and layout of the books. Adobe suite---a combination of design software was a tool that I often used in my machine. These tools includes Adobe Photoshop, Adobe Indesign and Adobe Illustrator. I prepared the text in Microsoft word and  imported it into Indesign for typesetting and layout. I used photoshop to clean and polish the image before I insert them into the Indesign document. I created and edited vector graphics required in the document with illustrator. Combining these tool helped me to produce high quality publishing products. 

> Traditionally books are often written with LaTeX or Microsoft Word. Either of these tools will make writing books a one-way trip and you cannot turn back: if you choose LaTeX, you typically end up only with a PDF document; if you work with Word, you are likely to have to stay in Word forever, and may also miss the many useful features and beautiful PDF output from LaTeX.
> @bookdown

The ability to reproduce the document in multiples outputs sparked my mind to start exploring the new way of authoring books and writing manuscripts. And R became the software of choice. I then discovered R has a nifty package called **Rmarkdown** written by @rmarkdown, which make writing books and manuscript for publications much easier than traditional tools such as Indesign, LaTeX and Word. Rmakrdown documents facilitates reproducible research because they handle `plain text` with `code` in the same document. 

I recent started learning a powerful **bookdown** packages for writing and authoring book. The bookdown package writen by @bookdown is based on R markdown package [@rmarkdown] and inherits the simplicity of the Markdown syntax. The package allows to produce multiple types of output formats like PDF, HTML, Word, EPUB, and Mobi. It has also features like for numbering and cross-referencing figures, tables, sections and equations, and inserting parts and appendices to create elegant and appealing HTML book pages. This functions offered by these packaged changed my  workflow of writing books and manuscripts for publications. 

I never waited and started working on these packages. I decided to start with our hidden under the shelf dissertations.  The dissertations from [Nyamisi Peter](https://lugoga.github.io/thesis_master_nyamisi/) and [Masumbuko Semba](https://lugoga.github.io/master_thesis/) as an example of using R package bookdown and rmarkdown to publish books. Even the blog that your reading comes from the **blogdown** package [@blogdown]

I have no more word but quotes from @bookdown

> The combination of R (https://www.r-project.org), Markdown, and Pandoc (http://pandoc.org) makes it possible to go from one simple source format (R Markdown) to multiple possible output formats (PDF, HTML, EPUB, and Word, etc.). The bookdown package is based on R Markdown, and provides output formats for books and long-form articles, including the GitBook format, which is a multi-page HTML output format with a useful and beautiful user interface. It is much easier to typeset in HTML than LaTeX, so you can always preview your book in HTML, and work on PDF after the content is mostly done. Live examples can be easily embedded in HTML, which can make the book more attractive and useful.

### References
