---
title: 'Programming: An Essential Skills for Scientists'
author: Masumbuko Semba
date: '2018-11-23'
slug: programming-an-essential-skills-for-scientists
categories:
  - R
tags:
  - R
  - Masumbuko Semba

bibliography: [blog.bib, argo.bib]
csl: apa.csl
link-citations: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, comment="")
```

## Introduction

In recent years, there's been an admirable push to get more people to learn programming. But if I've never been exposed to programming, why should I invest all of the effort to learn? What's in it for me? When I was confronted with data limitation challenge in spreadsheet [@brown], and the issue of repeating the same process over and over again, I decided to learn to program. I started learning R--- a statistical and graphical software [@james]. I then moved to Python [@langtangen], later to Matlab [@trauth]. But now, I do nearly all of my data work in R. Trust me---because I have been there, a little programming skills obtained by learning R has helped me to do so much more with data than I used to do with out--of--the--box--software. 

The skills of knowing how to progrm were apparent recently when I submitted a manuscript in a peer reviewed journal to be considered for publication. After a month of review, they gave me the feedback of the review with major revisions that should be done within 21 days. Because I had analysed the data and prepared the manuscript with plain text **rmarkdown** developed by Allaire and his collegues [-@rmarkdown]. Although the revision 85 of the origin manuscript, it just only took me three days to address all the major issues. After resubmission, the in--house checked and returned the revised version simply because I had not included the data underlying the findings. They asked me to provide these data as *supporting information* within three weeks. I instantly uploaded the data along with the *script*^[R script written that automate the execution of analysis of the manuscript] containing codes used for the manuscript. That was easy for me becasue I coded the work. That was easier and found myself relaxed---a glimpse of programming! I now realize how much productive I have become at work with this programming skills and I how the skills make my routine easy, constistency and reproducible.

Using a programming language like R [@r] can look cryptic at first. That is true, like any language, you can not immediately start a conversation. You must know the basics first and the way you practice make you fluency in that language. Honestly, I found learning programming is hard!. There is definitely a learning curve, however, putting in a little time is rewarding in long run as it make routine task much easier. The routine tasks that used to take hours of work can now be done within few minutes with code. This code can be replicated to solve other task as well. The other good reason I found about programming is that once you muster one language, it is much easier to learn others because their share almost similar building blocks with minor adjustments.

In summary knowing to code can make you 10 times faster in your daily routine. Because programming help you to automate tedious tasks of cleaning and preparing the data that you would otherwise need to do by hand. If you know how to program, computer-related tasks that used to take you a week to finish will now take only a few hours---What a relief?

Programming *stretch your brain* and allows you to discover more creative solutions than your colleagues who don't know how to program. It lets you go beyond simply using the tools and data sets that everyone else around you uses, to transcend the limitations that your peers are stuck with. For example, you'll be able to write programs to automatically acquire data from new sources, to clean, reformat, and integrate that data with your existing data, and to implement far more sophisticated analyses than your colleagues who can only use pre--existing tools.


## Cited resources
