---
title: 'A shiny WebApp of the Lake Tanganyika '
author: Masumbuko Semba
date: '2020-07-31'
slug: a-shiny-webapp-of-the-lake-tanganyika
categories: []
tags:
  - shiny
  - R
  - Masumbuko Semba
---

### Introduction
**Shiny** is an R package that was created by Joe Cheng. It wraps R code into interactive web applications so R coders do not need to learn HTML, CSS or JavaScript. This tool is powerful and useful, tool available to users of R. **Shiny** provides a framework for building interactive web apps that can be used for visualization, exploratory data analysis, data quality control – really anything that could benefit from an interactive environment. Shiny applications are immeasurably useful for helping users grasp information easily by interacting and querying the app.


This post will not go into the basics of Shiny. There are many resources on the web for getting started, and of particular value is the [RStudio Shiny gallery](https://shiny.rstudio.com/gallery/). However, I will show you the app we just created to help people in the region visualize and make sense of the data in Lake Tanganyika. 

### The App
You can access the app through this [link](https://semba.shinyapps.io/phyto_abundance/), but I also embed it in this post:

<iframe id="example1" src="https://semba.shinyapps.io/phyto_abundance/" 
style="border: non; width: 100%; height: 400px" 
frameborder="0">
</iframe> 